name: Build Pebble Watchface

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Pebble SDK
        run: pip3 install pebble-tool

      - name: Build
        run: pebble build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tipsy-watchface
          path: build/*.pbw
