name: Build Pebble Watchface

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Pebble SDK
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip3 install pebble-sdk

      - name: Build Watchface
        run: pebble build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pbw
          path: build/*.pbw
